import React, { useState } from 'react';
import {Link, useLocation, useNavigate} from 'react-router-dom';
import { useAppDispatch } from "../../state/store.ts";
import { verifyOtp } from "../../state/Authentication/Reducer.ts";
import {Button, TextField, Container, Typography, Box, Card, CardContent} from '@mui/material';

const VerifyOtp = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const dispatch = useAppDispatch();

    const [otp, setOtp] = useState('');
    const username = location.state?.username;

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();

        if (!username) {
            console.error('Username is missing!');
            return;
        }

        try {
            await dispatch(verifyOtp({ code: otp, username })).unwrap();
            navigate('/');
        } catch (error) {
            console.error('OTP verification failed:', error);
        }
    };

    const isOtpValid = otp.length === 6;

    return (
        <Box
            sx={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                minHeight: '100vh',
                backgroundColor: "#f0f2f5",
            }}
        >
            <Container maxWidth="sm">
                <Card sx={{ borderRadius: 3, boxShadow: 5, backgroundColor: "white" }}>
                    <CardContent>
                    <Typography variant="h4" align="center" sx={{ marginBottom: 3, fontWeight: 'bold' }}>
                        Two-Factor Authentication
                    </Typography>
                    <Typography variant="body1" align="center" sx={{ marginBottom: 3 }}>
                        Enter the 6-digit validation code generated by your authentication app
                    </Typography>
                    <form onSubmit={handleSubmit}>
                        <TextField
                            label="OTP Code"
                            variant="outlined"
                            fullWidth
                            type="text"
                            value={otp}
                            onChange={(e) => setOtp(e.target.value)}
                            placeholder="Enter OTP code"
                            sx={{ marginBottom: 3 }}
                            inputProps={{ maxLength: 6 }} // Giới hạn độ dài tối đa là 6
                        />

                        <Button
                            variant="contained"
                            type="submit"
                            fullWidth
                            disabled={!isOtpValid}  // Disable nếu OTP không hợp lệ (dài 6 ký tự)
                            sx={{
                                color: (!otp || otp.length !== 6) ? "#757575" : "#fff",
                                "&:disabled": {
                                    backgroundColor: "#bdbdbd", // Màu nền khi disabled
                                    color: "#757575" // Màu chữ khi disabled
                                }
                            }}
                        >
                            Verify
                        </Button>
                    </form>
                    {/* Link xác thực bằng email */}
                    <Box sx={{ marginTop: 2, textAlign: 'center' }}>
                        <Typography variant="body2">
                            <Link
                                to={`/account/verify-email?username=${encodeURIComponent(username)}`}
                                style={{ color: '#1976d2', textDecoration: 'none', fontWeight: 'bold' }}
                            >
                                Using another way to verify
                            </Link>
                        </Typography>
                    </Box>
                    </CardContent>
                </Card>
            </Container>
        </Box>
    );
};

export default VerifyOtp;
